version: '3.8'
services:

  p1monitor:
    hostname: p1mon
    image: mclaassen/p1mon
    ports:
      - 81:80
    volumes:
      - ./alldata/data:/p1mon/data
      - ./alldata/usbdisk:/p1mon/mnt/usb
      - ./alldata/mnt/ramdisk:/p1mon/mnt/ramdisk
    tmpfs:
      - /run
      - /tmp
    devices:
      - "/dev/ttyS0:/dev/ttyUSB0"
    restart: unless-stopped
    #    environment:
      # Use environment variables as needed. Check https://marcel.duketown.com/p1-monitor-docker-versie/ for more information
      #- DISABLECPUTEMP=true
      #- SOCAT_CONF="pty,link=/dev/ttyUSB1,rawer,group-late=dialout,mode=660 tcp:192.168.1.200:23,retry=forever,interval=30"
      #- PROXYPATH=marcel
      #- PROXYPATH=marcel
      #- GPIOZERO_PIN_FACTORY=pigpio
      #- PIGPIO_ADDR=raspberry.local
