#!/bin/bash
source /p1mon/scripts/pythonenv.sh
eval "python3 /p1mon/scripts/P1Weather.py $@" # @ is all the parameters we got on the command line & will leave bash script, you can't kill it on the command line, use kill instead. 
