<?php
function strIdx($_index) {

        $array = array(
/* 000 */    '0 index voor test.',
/* 001 */   'De P1 poort op de slimme meter is een seriële interface die afhankelijk van de het type slimme meter anders ingesteld moet worden.<br><br>In Nederland is het DSMR 3 protocol 9600 7E1 (7 databits, even parity, 1 stop bit) of DSMR 4 protocol 115200 8N1 (8 databits, geen parity, 1 stop bit) gebruikelijk.<br><br>',
/* 002 */   'Omdat de slimme meter ongeveer elke 10 seconden de gegevens stuurt kan het tussen de 30 tot 60 seconden duren voordat de status correct wordt weergegeven.',
/* 003 */   'Het overzicht van de wifi access points (essid’s) wordt elke 60 seconden aangepast.<br>Mocht de wifi naam er niet tussen staan wacht dat 1 minuut en ververs de pagina (bijvoorbeeld via herstel optie.)<br><br>Het wijzingen van de wifi instellingen kan enkele minuten duren.<br><br>Mocht de Wifi niet actief worden herstart de Raspberry Pi dan via het configuratie systeem menu.',
/* 004 */   'Tarieven in euro\'s per geleverde kWh , kubieke meter gas of water.<br><br>De vastrechtkosten worden opgeteld bij het kosten voor geleverde kWh, gas of water.',
/* 005 */    'Zet de de Rasberry Pi uit via deze opties om te voorkomen dat er data verloren gaat of corrupt raakt.<br><br>Na wissen van het wachtwoord wordt aanbevolen het wachtwoord opnieuw in te stellen.',
/* 006 */    'Database is de optie voor het delen van historische data. De ontwikkeloptie geeft toegang tot alle bestanden en moet vermeden worden. Uit is de standaard optie.',
/* 007 */   'Met export worden alle gegevens uit de SQLite database naar SQL statements in een zip file weggeschreven. Het exporteren is bedoeld om de gegevens veilig te stellen als er een nieuwe versie van P1 monitor uitkomt of als back-up. Importeren is bedoeld voor het inlezen van eerder gemaakte export bestanden en werkt alleen met een P1 monitor exportfile.',
/* 008 */   'Klik op de link voor een voorbeeld van de data die gelezen kan worden via de API. De help extensie van de API geeft uitleg.',
/* 009 */     'Het de-activeren van schermen maakt het mogelijk bepaalde schermen uit de userinterface(UI)te verwijderen. <br><br>Waarden instellen UI elementen maakt het mogelijk om een subset van grenswaarden in te stellen.<br><br> Als je een eigen userinterface wil gebruiken als alternatief van de standaard interface selecteer dan de optie eigen userinterface.  Als deze ingeschakeld wordt dan wordt standaard als eerste pagina /www/custom/p1mon.php weergegeven. Maak alleen gebruik van de API calls en eigen javascript of andere bestanden. De bronnen uit de standaard interface kunnen per versie worden veranderd. ',
/* 010 */     'De weer informatie wordt verkregen via openweathermap.org website. Om deze website te kunnen gebruiken moet je een gratis account aanmaken op de website en een API key verkrijgen. Dit is erg eenvoudig zie de openweathermap.org website.<br><br>Voer de API key in en de stad. Voer bij de stad minimaal drie karakters in. Je kunt tevens een landcode opgeven in het formaat stad, landcode bijvoorbeeld amsterdam,nl vs amsterdam,us om te voorkomen de verkeerde locatie wordt ingesteld.<br><br> je kunt teven de stad id invoeren als het niet lukt om via de naam van de stad de juiste locatie in te stellen. De stad id kun je achter halen via de site van openweathermap.org. Zoek een stad. Als de pagina verschijnt op de site achter de url de stad id. Voor Alkmaar is dit bijvoorbeeld https://openweathermap.org/city/2759899',
/* 011 */   'De timer instelling geven de mogelijkheid om het tijdstip van de back-up in te stellen.  Het is gebaseerd op de crontab syntax. Voor meer details zie http://www.cronjob.nl/.<BR><BR>Beweeg je muis over de velden voor extra informatie.',
/* 012 */   'FTP is een niet versleutelde verbinding, FTPS is een versleutelde verbinding die de inlog gegevens beveiligd, alleen expliciet FTPS over poort 21 wordt ondersteunt, impliciet over poort 990 niet. SFTP is een verbinding gebaseerd op SSH en is de meest veilige optie.',
/* 013 */    'Account de naam van ftp inlog naam (account) vaak is dit in het formaat naam@domein.xxx',
/* 014 */   'Het wachtwoord dat bij de het ftp account hoort.',
/* 015 */   'Folder waar je de back-up’s naar toe wil kopiëren, het veld mag ook leeg zijn.',
/* 016 */   'IP adres of domeinnaam (ftp@mijdomein.nl o.i.d) van de ftp server.',
/* 017 */   'Dit is normaal poort 21 en hoeft niet aangepast te worden maar kan nodig zijn als je een niet standaard ftp server gebruikt. Deze poort instelling werkt alleen voor FTP!',
/* 018 */   'Aantal versies die je wil bewaren, na het bereiken van dit aantal wordt de oudste back-up gewist.',
/* 019 */   'De laatste keer dat de timer een back-up heeft gestart.',
/* 020 */   'De laatste keer dat de back-up succesvol is afgerond.',
/* 021 */   'Hier worden meldingen weergegeven die de backup server rapporteert.',
/* 022 */   'Test de back-up apart van de timer.',
/* 023 */   'Dit is de 1.8.1 waarde ook wel laag/dal/nacht/tarief 1 genoemd (Nederland).',
/* 024 */   'Dit is de 1.8.2 waarde ook wel hoog/piek/dag/tarief 2 genoemd (Nederland).',
/* 025 */   'Dit is de 2.8.1 waarde ook wel laag,dal/nacht/tarief 1 genoemd (Nederland).',
/* 026 */   'Dit is de 2.8.2 waarde ook wel hoog/piek/dag/tarief 2 genoemd (Nederland).',
/* 027 */   'Het gas telegramcodenummer is het nummer van de gasmeting, normaal is dit een gasmeting met het nummer 0-1 zoals bij de codes 0-1:24.2.1, 0-1:24.3.0 of 0-1:24.2.3. Deze optie stelt het nummer achter het streepje in. Bijvoorbeeld een 2 wordt dan 0-2:24.2.1',
/* 028 */   'Grenswaarde kosten is het bedrag wat je per maand aan kosten maakt of wil maken. In de kostenoverzicht levert dit een grenslijn op die aangeeft of je over of onder je maandbedrag blijft.',
/* 029 */   'Sommige slimme meters maakt gebruik van een controle methode(CRC) waarmee vastgesteld kan worden of de P1 data correct is verstuurd. Mocht je problemen ondervinden dan kan deze controle aan of uitgezet worden. Voor meters zonder CRC (geen vier karakters achter het einde telegram karakter !) uitzetten.',        
/* 030 */   'Om Dropbox te kunnen gebruiken moet de P1 monitor beperkt toegang krijgen tot een Dropbox account. Er wordt alleen toegang gevraagd tot de /apps/p1monitor folder. Klik op het Dropbox icoon volg de instructies van Dropbox en knip en plak het autorisatie token.<br><br>De optie date delen met Dropbox is een test en wordt mogelijk in de toekomst gebruikt om een P1 monitor app te voorzien van gegevens.',
/* 031 */   'De laatste keer dat er succesvol data naar Dropbox is gekopieerd.',
/* 032 */   'Statusmelding van Dropbox.',
/* 033 */   'Met versie controle wordt automatisch periodiek gecontroleerd of er een nieuwe versie beschikbaar is. Deze optie staat om privacy reden standaard uit. Als de optie aan staat dan word je publieke IP-adres gedeeld met ztatz.nl. We doen niets met het IP-adres en wissen deze periodiek.',
/* 034 */   'De UDP broadcast deamon verstuurt ongeveer elke 10 seconden een JSON netwerkbericht (UDP broadcast op poort 40721).',
/* 035 */   'Systeem ID is een unieke code van de P1 monitor. Deze code wordt gebruik om onderscheid te maken tussen verschillende P1 monitor installaties. De code wordt bijvoorbeeld gebruik in back-up en in Dropbox data bestanden.',
/* 036 */   '"Voorspelling aan in de UI" probeert in die gevallen waar de data nog niet van is gemeten een voorspelling te doen. Dit is een inschatting geen absolute waarde en beperkt betrouwbaar.',
/* 037 */   'De upgrade assistent helpt bij het migreren/upgrade naar een nieuwere versie. Om de upgrade assistent te kunnen gebruiken heb je een USB-stick nodig die met FAT of FAT32 is geformatteerd. NFTS , exFat of andere filesystems worden niet ondersteunt. In principe kan elke USB-drive worden gebruikt tussen de 1Gb en 32 Gb. De daadwerkelijke ruimte die nodig is zeer beperkt en minder dan 100Mb. Bij het activeren van de Upgrade assistent wordt gezocht naar een geschikte USB-stick in een van de USB-poorten en de database en andere configuratie data gekopieerd naar de USB-stick. Bij de volgende keer dat de P1 monitor wordt gestart wordt de data van de USB-stick naar het SDHC-kaartje gekopieerd. Dit is een eenmalig actie waarbij de data van de USB-stick wordt verwijderd. Het is belangrijk te begrijpen dat het activeren van de Upgrade assistent waarbij de USB-stick in de Raspberry Pi blijft de database overschreven wordt met de (oude) data van de USB-stick. De USB-stick is na een upgrade leeg en bevat geen data meer.  De upgrade wordt in twee fasen gedaan. In de eerste fase worden de basis configuratie gegeven overgezet en Pi herstart. Na de herstart wordt op de achtergrond een import uitgevoerd die afhankelijk van de hoeveelheid data wel tot een kwartier in beslag kan nemen.  <br><br><span style="color:red">Bij upgrade mag de Pi dan ook de eerste 20 minuten niet herstart worden.</span><br><br>Mocht je USB-stick willen wissen dan kun je de folder p1monitor wissen.<br><br><span style="color:red">Het wordt aanbevolen een export te doen van de data als noodmaatregel, mocht er een probleem optreden met de upgrade assistent.</span><br><br>',
/* 038 */   'De gasmeter stand',
/* 039 */   'Moment van hoogste verbruik',
/* 040 */   'Piek verbruikswaarde',
/* 041 */   'Verbruik vandaag.',
/* 042 */   'Kosten vandaag gas, elektriciteit en water',
/* 043 */   'Moment van hoogste levering',
/* 044 */   'Piek leveringswaarde',
/* 045 */   'Levering vandaag.',
/* 046 */   'Opbrengsten vandaag.',
/* 047 */   'Kosten vandaag elektriciteit en water',
/* 048 */   'Kosten vandaag gas',
/* 049 */   'Configuratie via het Internet staat toe dat een browser met een Internet IP-adres aanpassingen kan maken in de configuratie of bepaalde afgeschermde pagina’s toegankelijk zijn, deze zijn normaal alleen met een RFC1918 IP-adres te gebruiken. De optie is gemaakt omdat er situaties zijn waar internetadressen op het lokale LAN worden gebruikt.',
/* 050 */   'Naam van de email inlognaam (account) vaak is dit in het formaat naam@domein.nl',
/* 051 */   'Het wachtwoord van het email account.',
/* 052 */   'IP-adres of domeinnaam (smtp.gmail.com / mail.ztatz.nl o.i.d.) van de mailserver.',
/* 053 */   'Dit is de poort die je email provider gebruikt voor het versleuteld versturen van email. Je email provider bepaalt deze poort. Voor Gmail is dit 465.',
/* 054 */   'Dit is de poort die je email provider gebruikt voor het gedeeltelijk versleuteld versturen van email. Je email provider bepaalt deze poort. Voor Gmail is dit 587.',
/* 055 */   'Dit is de normale poort voor email verkeer(onveilig). Normaal is dit poort 25. ',
/* 056 */   'Het onderwerp van de notificatie e-mails die het standaard onderwerp vervangt. ',
/* 057 */   'Lijst van email adressen van de ontvangers gescheiden met een spatie.',
/* 058 */   'Lijst van email kopie adressen (CC van de ontvangers gescheiden met een spatie.',
/* 059 */   'Lijst van email blinde kopie adressen (BCC) van de ontvangers gescheiden met een spatie.',
/* 060 */   'De zender van de notificatie e-mails die de standaard tekst vervangt, houdt dit veld leeg voor de standaard tekst.',
/* 061 */   'De hoeveelheid tijd in de seconden dat er gewacht wordt op een antwoord van de email server.',
/* 062 */   'Vul hier de instellingen in van de email provider die je wilt gebruiken. <br><br>Mocht je gebruik willen maken van een Gmail account dan moet Multi-factor authenticatie uit staan en toegang tot minder veilige apps moet worden toegestaan. <br><br> <span style="color:red">Er zijn soms problemen met het gebruik van Gmail, dit wordt onderzocht maar daar is nog geen oplossing voor.</span>',
/* 063 */   'Notificatie als er geen slimme meter data wordt ontvangen.',
/* 064 */   'Dag/nacht mode laag en hoog tarief verwerking aanpassen tussen België en Nederland. Alleen aanpassen als de dag en nacht waarden verwisseld worden.',
/* 065 */   'Dit is de 1.8.1 waarde ook wel hoog/piek/dag/tarief 2 genoemd (België)',
/* 066 */   'Dit is de 1.8.2 waarde ook wel laag/dal/nacht/tarief 1 genoemd (België)',
/* 067 */   'Dit is de 2.8.1 waarde ook wel hoog/piek/dag/tarief 2 genoemd (België)',
/* 068 */   'Dit is de 2.8.2 waarde ook wel laag/dal/nacht/tarief 1 genoemd (België)',
/* 069 */   'Screensaver met de in en uitschakeltijden, als de muis bewogen wordt zal de screensaver stoppen. Uit wil zeggen niet inschakelen of automatische uitschakelen. De optie geldt niet voor de instellingsschermen.',
/* 070 */   'Met de terug levering schakelaar kan een instelbare GPIO-pin worden geactiveerd om zo een bijvoorbeeld een boiler in te schakelen als er een ingesteld vermogen wordt opgewekt. De volgende parameters zijn beschikbaar. Grenswaarden voor het in of uitschakelen. De periode van de gemiddelde waarde voor de grenswaarden. Minimale tijd dat in of uitgeschakeld wordt. GPIO pin die wordt gebruikt. Het aan of uitzetten van de terug levering. Of de ingesteld GPIO-pin activeren voor test o.i.d. Voor het selecteren van de GPIO-pin gebruik de nummering GPIOnn GPIO18 is dan pin 12. Zie onderstaande afbeelding.',
/* 071 */   'Database wissen wist alle database data inclusief de configuratie alsof het een nieuwe installatie is. Na het wissen moet alles opnieuw ingesteld worden ook al lijkt het te werken. Let op dit kan enkele minuten duren, geduld aub.',
/* 072 */   'Met de tariefschakelaar kan via een ingesteld GPIO-pin tijdens de ingestelde periodes worden geschakeld tijdens het piek of dal tarief. De ingevoerde schakelperioden worden bij elkaar gevoegd.',
/* 073 */   'De watermeter stand',
/* 074 */   'Stuur een test email met de ingestelde parameters.',
/* 075 */   'Wat is kilowattuur per minuut, hoe kan dit?  De energie meter geeft aan wat het verbruik is per kWh.  Volgends de definitie is dit 1 Watt (W) staat gelijk aan 1 Joule (J) per seconde (s): 1 W = 1 J/s.  1 kilowatt = 1.000 Watt.  1 kWh is wat een apparaat met een vermogen van 1.000 Watt (1 kW) in één uur verbruikt.  In de P1 monitor nemen we de waarde van kWh op tijdstip T1 en tijdstip T2 (dat is T1 + 1 minuut)  waarbij we de KWh waarde van T2 – T1 aftrekken. Stel T1 is 10kWh en T2 is 10.005 kWh dan is er tijdens die minuut dus 10.005 – 10kWh verbruikt is 0.005 kWh.  De “echte” kWh waarde wordt dan 0.005 * 60 minuten wat 0,3kWh over een uur.',
/* 076 */   'MQTT (Message Queue Telemetry Transport) is een client met broker opzet. De P1 monitor werkt als MQTT client en is geen MQTT broker. MQTT werkt met zogenaamde topics om de data bronnen aan te geven die naar de broker worden gestuurd. Het scherm “MQTT published topics” geeft welke topics ondersteunt worden. Deze zijn aan te passen met de schakelaars.<br><br>
<b>client ID:</b> mag leeg zijn dan wordt er automatisch een client ID gemaakt.<br> <b>topic voorvoegsel:</b> mag leeg zijn dan wordt p1monitor gebruikt.<br> <b>broker servernaam / IP:</b> naam of ip adres van de MQTT broker.<br> <b>broker IP poort:</b> TCP/poort van de broker meestal 1883.<br> <b>broker keep alive tijd:</b> tijd in seconden dat gecontroleerd wordt of verbinding met de broker in orde is.<br> <b>broker gebruikers naam /  broker gebruikers wachtwoord:</b> Als een broker om een naam en wachtwoord nodig heeft anders kunnen de velden leeg blijven.<br> <b>QoS (Quality of Service)</b> en <b>protocol versie:</b> raadpleeg de MQTT specificatie.',
/* 077 */   'Niet alle slimme meters geven fase informatie door en sommige slimme meters een beperkte set van volt, ampère of vermogen (Watt) waarden.  Als deze informatie niet doorgegeven wordt dan zullen de meetwaarden als nul (0) worden weergegeven.',
/* 078 */   'Verberg of laat een grafiek zien.',
/* 079 */   'Datapunten (samples) terug in de tijd.',
/* 080 */   'Datapunten (samples) vooruit in de tijd.',
/* 081 */   'Aantal datapunten instellen.',
/* 082 */   'De historische fase data is relatief veel data. Als de historische data niet gebruikt wordt dan is het verstandig om deze optie uit te zetten om de belasting  op de database en de processor te verminderen. Belangrijk: niet alle slimme meters geven fase informatie door.  In het telegram moet minimaal een van de volgende codes voorkomen 1-0:21.7.0, 1-0:41.7.0, 1-0:61.7.0, 1-0:22.7.0, 1-0:42.7.0, 1-0:62.7.0, 1-0:32.7.0, 1-0:52.7.0, 1-0:72.7.0, 1-0:31.7.0, 1-0:51.7.0, 1-0:71.7.0.',
/* 083 */   'Met de UI labels kan een andere tekst in schermen worden ingesteld. Zonder invoer wordt de standaard tekst gebruikt.',
/* 084 */   'De hoeveelheid water in de elke puls vertegenwoordigd.  Normaal is dit 1 Liter per puls.',
/* 085 */   'Het aantal kubieke meter water dat op watermeter staat bij de opgegeven watermeter timestamp.',
/* 086 */   'De datum van de watermeterstand uit het verleden. Vanaf deze datum wordt de watermeterstand opgeteld bij de gemeten liters.',
/* 087 */   'Zet deze schakelaar op aan om de watermeterstand te verwerken in de database. Vergeet niet op opslaan te drukken rechts boven aan de pagina',
/* 088 */   'Dit geeft status van de aanpassing in de database, terwijl de database wordt aangepast.',
/* 089 */   'De totale watermeter stand na of voor werking van de watermeter reset.',
/* 090 */   'De laatste keer dat een watermeter puls verwerkt is.',
/* 091 */   'Als er geen gegevens worden weergegeven dan kan het zijn dat de opslag van historische gegevens niet aangezet is of dat de slimme meter geen fasegegevens doorgeeft. In het configuratie menu kan op de pagina bestanden de optie worden geactiveerd.',
/* 092 */   'De kWh waarde in de elke puls vertegenwoordigd. Dit is afhankelijk van de specifieke meter. Raadpleeg de kWh meter handleiding.',
/* 093 */   'De kWh meterstand opgegeven bij de ingevoerd timestamp.',
/* 094 */   'Zet deze schakelaar op aan om de kWh meterstand te verwerken in de database. Vergeet niet op opslaan te drukken rechts boven aan de pagina.',
/* 095 */   'De laatste keer dat een kWh S0 puls verwerkt is.',
/* 096 */   'De datum van de kWh meterstand uit het verleden. Vanaf deze datum wordt de kWh meterstand opgeteld bij de gemeten kWh waarden.',
/* 097 */   'De kWh stand na of voor werking van de kWh meter reset.',
/* 098 */   'Kopieert het P1 telegram naar het clipboard zodat het telegram in een ander document of voor bijvoorbeeld een ondersteuningsvraag kan worden gebruikt.',
/* 099 */   'Bruto terug levering is wat de zonnepanelen, windmolen en enz. opwekken exclusief je eigen verbruik. Netto terug levering is wat er daadwerkelijk aan het energienetwerk via de slimme meter wordt terug geleverd.', 
/* 100 */   'Dit overzicht geef  de log bestanden weer die de P1 monitor aanmaakt. Kies uit het overzicht van <b>beschikbare log bestanden</b>. Klik op de regel en dan wordt onderaan de pagina voor het geselecteerde log bestand de inhoud weergegeven.<br><br>Met de knoppen <b>automatisch</b> vernieuwen worden de overzichten automatisch ververst.<br><br>Klik ergens in het overzichten en gebruik vervolgens de toetsencombinatie <b>ctrl + c</b> om de inhoud te kopiëren en ga vervolgens naar een spreadsheetprogramma zoals Excel om de inhoud daar in te plakken.<br><br>Met de download knoppen kan een kopie van het log bestand in verschillende formaten worden gemaakt.',
/* 101 */

);

    if(!isset($array[$_index])) {
        echo 'tekst voor index '. $_index . ' niet gevonden! Meld dit op www.ztatz.nl.';
    } else {
        echo $array[$_index];
    }
}
?>